from .crud_user import user
from .crud_department import department
from .crud_student import student
from .crud_lecturer import lecturer
from .crud_course import course
from .crud_academic_session import academic_session
from .crud_course_assignment import course_assignment
from .crud_attendance_session import attendance_session
from .crud_attendance_record import attendance_record
