"""Add cascade delete to foreign keys

Revision ID: 2f5c2dea2df7
Revises: 41c9d92795e3
Create Date: 2026-06-27 23:52:05.481315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5c2dea2df7'
down_revision: Union[str, Sequence[str], None] = '41c9d92795e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendance_records_session_id_fkey'), 'attendance_records', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_records', 'attendance_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('attendance_sessions_course_assignment_id_fkey'), 'attendance_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_sessions', 'course_assignments', ['course_assignment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_sessions_course_assignment_id_fkey'), 'attendance_sessions', 'course_assignments', ['course_assignment_id'], ['id'])
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_records_session_id_fkey'), 'attendance_records', 'attendance_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
