"""add_dates_to_academic_sessions

Revision ID: 41c9d92795e3
Revises: 860c5589ff08
Create Date: 2026-06-24 18:20:36.484186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c9d92795e3'
down_revision: Union[str, Sequence[str], None] = '860c5589ff08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_sessions', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('academic_sessions', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_sessions', 'end_date')
    op.drop_column('academic_sessions', 'start_date')
    # ### end Alembic commands ###
