"""add_geofencing_fields

Revision ID: 860c5589ff08
Revises: b5105f0d2367
Create Date: 2026-06-24 17:09:13.531277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860c5589ff08'
down_revision: Union[str, Sequence[str], None] = 'b5105f0d2367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('attendance_records', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('geofencing_enabled', sa.Boolean(), nullable=False))
    op.add_column('attendance_sessions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('radius_meters', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_sessions', 'radius_meters')
    op.drop_column('attendance_sessions', 'longitude')
    op.drop_column('attendance_sessions', 'latitude')
    op.drop_column('attendance_sessions', 'geofencing_enabled')
    op.drop_column('attendance_records', 'longitude')
    op.drop_column('attendance_records', 'latitude')
    # ### end Alembic commands ###
