"""Add index to full_name and staff_id

Revision ID: e083282786b8
Revises: 2f5c2dea2df7
Create Date: 2026-06-29 20:00:36.182473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e083282786b8'
down_revision: Union[str, Sequence[str], None] = '2f5c2dea2df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lecturers_staff_id_key'), 'lecturers', type_='unique')
    op.create_index(op.f('ix_lecturers_staff_id'), 'lecturers', ['staff_id'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_lecturers_staff_id'), table_name='lecturers')
    op.create_unique_constraint(op.f('lecturers_staff_id_key'), 'lecturers', ['staff_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
