from .user import User
from .department import Department
from .student import Student
from .lecturer import Lecturer
from .course import Course
from .academic_session import AcademicSession
from .course_assignment import CourseAssignment
from .attendance_session import AttendanceSession
from .attendance_record import AttendanceRecord
